/** Stable machine-readable rejection codes. UIs should branch on these, not on messages. */
export const ERROR = Object.freeze({
  UNKNOWN_COMMAND: "UNKNOWN_COMMAND",
  UNAUTHORIZED: "UNAUTHORIZED",
  INVALID_INPUT: "INVALID_INPUT",
  INVALID_CONFIG: "INVALID_CONFIG",
  DUPLICATE_ID: "DUPLICATE_ID",
  NOT_FOUND: "NOT_FOUND",
  NOT_ENOUGH_PARTICIPANTS: "NOT_ENOUGH_PARTICIPANTS",

  AUCTION_NOT_IN_SETUP: "AUCTION_NOT_IN_SETUP",
  AUCTION_NOT_LIVE: "AUCTION_NOT_LIVE",
  AUCTION_PAUSED: "AUCTION_PAUSED",
  AUCTION_COMPLETED: "AUCTION_COMPLETED",

  LOT_IN_PROGRESS: "LOT_IN_PROGRESS",
  NO_ACTIVE_LOT: "NO_ACTIVE_LOT",
  PLAYER_NOT_AVAILABLE: "PLAYER_NOT_AVAILABLE",
  PLAYER_LOCKED: "PLAYER_LOCKED",
  ALREADY_SOLD: "ALREADY_SOLD",
  NOT_SOLD: "NOT_SOLD",
  NO_PLAYERS_LEFT: "NO_PLAYERS_LEFT",
  STALE_STATE: "STALE_STATE",

  INVALID_AMOUNT: "INVALID_AMOUNT",
  PRICE_BELOW_BASE: "PRICE_BELOW_BASE",
  INSUFFICIENT_PURSE: "INSUFFICIENT_PURSE",
  RESERVE_REQUIRED: "RESERVE_REQUIRED",
  SQUAD_FULL: "SQUAD_FULL",
  OVERSEAS_LIMIT: "OVERSEAS_LIMIT",
  ROLE_LIMIT: "ROLE_LIMIT",
  ROLE_MINIMUM_UNREACHABLE: "ROLE_MINIMUM_UNREACHABLE",

  NOTHING_TO_UNDO: "NOTHING_TO_UNDO",
});

export function fail(code, message) {
  return { code, message };
}
